org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=1.21.5
neoform_version=1.21.5-20250325.162830
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# NeoForge
neoforge_version=21.5.2-beta

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.127.0+1.21.5
mod_menu_version=14.0.0-rc.2

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=miniatures
mod_name=Miniatures
mod_version=1.7.12.33
mod_description=Sublimiter torture simulator!
sources_url=https://github.com/Noobanidus/miniatures
issues_url=https://github.com/Noobanidus/miniatures/issues
license_url=https://github.com/Noobanidus/miniatures/blob/HEAD/LICENSE
homepage_url=https://www.curseforge.com/minecraft/mc-mods/miniatures

# Publishing
mod_group_id=noobanidus.mods
curseforge_id=445521
maven_group=noobanidus.mods

forge_config_api_port=21.5.3

git_previous_commit=e61f68ac0beab7b936bc29b17608b6f889ad98bc
