org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx6500m

# Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 26.2)
neoform_version=26.1.2-1

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_version_range=[26.1.2.22-beta,)

# Fabric
fabric_loader_version=0.19.2
fabric_api_version=0.146.1+26.1.2
mod_menu_version=14.0.0-rc.2

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.5.0
asm_version=9.7
auto_service_version=1.0.1
resourceful_config_version=4.0.1
jade_version=26.0.5

## Mod Properties
mod_id=miniatures
mod_name=Miniatures
mod_version=2.8.13.34
mod_description=Sublimiter torture simulator!
sources_url=https://github.com/Noobanidus/miniatures
issues_url=https://github.com/Noobanidus/miniatures/issues
license_url=https://github.com/Noobanidus/miniatures/blob/HEAD/LICENSE
homepage_url=https://www.curseforge.com/minecraft/mc-mods/miniatures

# Publishing
mod_group_id=noobanidus.mods
curseforge_id=445521
maven_group=noobanidus.mods

git_previous_commit=e61f68ac0beab7b936bc29b17608b6f889ad98bc
