def generatedResources = file("src/generated")

sourceSets {
    generated {
        resources.srcDir generatedResources
    }
}

repositories {
        maven {
            name = "Fuzs Mod Resources"
            url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        }
}

dependencies {
    // REQUIRED
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation("net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}")

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras}"))

    implementation ("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api_port}") { transitive false }
}

architectury {
    common("fabric", "neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/miniatures.accesswidener")
}

jar {
    exclude "architectury.common.json"

    manifest {
        attributes 'Fabric-Loom-Remap': true
    }
}

sourcesJar {
    exclude "architectury.common.json"
}

def ENV = System.getenv()

publishing {
    tasks.publish.dependsOn build

    publications {
        mavenJava(MavenPublication) {

            artifactId project.archivesBaseName
            artifact remapJar
            artifact project.sourcesJar {
                archiveClassifier.set('sources')
            }

            pom {
                name = 'Miniatures'
                description = ''
                url = 'https://github.com/noobanidus/miniatures'

                scm {
                    connection = 'git:https://github.com/noobanidus/miniatures.git'
                    developerConnection = 'git:https://github.com/noobanidus/miniatures.git'
                    url = 'https://github.com/noobanidus/miniatures'
                }

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'noobanidus'
                        name = 'Noobanidus'
                        email = 'noobanidus+spam@gmail.com'
                    }
                }

            }
        }
    }

    repositories {
        maven {
            url "file:///" + System.getenv("local_maven")
        }
    }
}

task buildAndRelease{}
tasks.build.mustRunAfter tasks.clean
tasks.publish.mustRunAfter tasks.build
tasks.buildAndRelease.dependsOn(tasks.clean, tasks.build, tasks.publish)
