modLoader="javafml" 
loaderVersion="[2,)"
issueTrackerURL="https://github.com/noobanidus/miniatures/issues"
license="https://github.com/noobanidus/miniatures/blob/1.16/LICENSE"
[[mods]]
    modId="miniatures"
    version="${version}"
    displayName="Miniatures"
    displayURL="https://minecraft.curseforge.com/projects/miniatures"
    authors="Noobanidus"
    description="Summon a miniature version of yourself!"

[[dependencies.miniatures]]
    modId="minecraft"
    type="required"
    versionRange="${versionRange}"

 [[dependencies.miniatures]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"